spring:
  application:
    name: forohub

  datasource:
    url: jdbc:mariadb://localhost:3306/FOROHUB_DB
    username: user_test
    password: password_test

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS

  flyway:
    baselineOnMigrate: true

server:
  port: 8080

api:
  security:
    secret: ${JWT_SECRET:123456}
